package com.reasonix.agents.ui.theme

/**
 * 工具名「英文「中文」」映射（2026-08-06，对齐 RikkaHub 中文化习惯）。
 *
 * 在工具折叠标题处展示：英文原名「中文翻译」，如 bash「终端命令」。
 * 未收录的工具名原样展示（不强行翻译）。
 */
object ToolNames {
    private val MAP =
        mapOf(
            "bash" to "终端命令",
            "terminal" to "终端命令",
            "shell" to "Shell 命令",
            "read_file" to "读取文件",
            "write_file" to "写入文件",
            "edit_file" to "编辑文件",
            "multi_edit" to "批量编辑",
            "delete_file" to "删除文件",
            "delete_symbol" to "删除符号",
            "move_file" to "移动文件",
            "grep" to "搜索文本",
            "glob" to "查找文件",
            "ls" to "列出目录",
            "explore" to "探索代码库",
            "research" to "调研",
            "review" to "代码审查",
            "security_review" to "安全审查",
            "memory" to "记忆",
            "remember" to "保存记忆",
            "forget" to "清理记忆",
            "ask" to "提问",
            "ask_user" to "向用户提问",
            "todo_write" to "更新任务清单",
            "web_fetch" to "抓取网页",
            "complete_step" to "完成步骤",
            "code_index" to "代码索引",
            "lsp_definition" to "符号定义",
            "lsp_references" to "符号引用",
            "lsp_hover" to "类型提示",
            "lsp_diagnostics" to "编译诊断",
            "mcp__codebase0graph__search_code" to "代码图搜索",
            "mcp__codebase0graph__search_graph" to "代码图查询",
            "mcp__codebase0graph__get_code_snippet" to "代码片段",
            "mcp__codebase0graph__get_architecture" to "架构总览",
            "mcp__codebase0graph__trace_path" to "调用链追踪",
            "mcp__anysearch__search" to "网络搜索",
            "mcp__anysearch__batch_search" to "批量搜索",
            "mcp__anysearch__extract" to "网页提取",
            "mcp__anysearch__get_sub_domains" to "领域发现",
            "run_skill" to "调用技能",
            "read_skill" to "读取技能",
            "task" to "子任务",
            "fleet" to "并行子任务",
            "parallel_tasks" to "并行任务",
            "wait" to "等待任务",
            "bash_output" to "读取输出",

            // ── reasonix 实际工具集补充（2026-08-06 优化）──
            "web_search" to "网络搜索",
            "web_fetch_text" to "抓取网页",
            "github" to "GitHub 操作",
            "gh" to "GitHub CLI",
            "git" to "Git 操作",
            "git_diff" to "查看差异",
            "git_status" to "查看状态",
            "git_commit" to "提交",
            "git_push" to "推送",
            "git_log" to "提交历史",
            "read" to "读取文件",
            "write" to "写入文件",
            "edit" to "编辑文件",
            "create" to "创建文件",
            "list" to "列出文件",
            "find" to "查找文件",
            "search_files" to "搜索文件",
            "replace" to "替换内容",
            "patch" to "应用补丁",
            "run" to "运行命令",
            "execute" to "执行命令",
            "command" to "执行命令",
            "python" to "运行 Python",
            "python3" to "运行 Python3",
            "node" to "运行 Node",
            "npm" to "npm 命令",
            "docker" to "Docker 操作",
            "ssh" to "SSH 连接",
            "scp" to "SCP 传输",
            "curl" to "HTTP 请求",
            "wget" to "下载文件",
            "mkdir" to "创建目录",
            "rm" to "删除",
            "cp" to "复制",
            "mv" to "移动",
            "cd" to "切换目录",
            "pwd" to "当前目录",
            "cat" to "查看内容",
            "head" to "查看开头",
            "tail" to "查看结尾",
            "less" to "分页查看",
            "sort" to "排序",
            "uniq" to "去重",
            "wc" to "统计",
            "sql" to "SQL 查询",
            "mysql" to "MySQL 查询",
            "postgres" to "PostgreSQL",
            "redis" to "Redis 操作",
            "kubectl" to "Kubernetes",
            "helm" to "Helm",
            "terraform" to "Terraform",
            "ansible" to "Ansible",
            "systemctl" to "系统服务",
            "journalctl" to "日志查看",
            "df" to "磁盘空间",
            "du" to "目录大小",
            "free" to "内存查看",
            "ps" to "进程列表",
            "top" to "进程查看",
            "kill" to "结束进程",
            "ping" to "网络测试",
            "netstat" to "网络状态",
            "ip" to "IP 配置",
            "jq" to "JSON 处理",
            "sed" to "流编辑",
            "awk" to "文本处理",
            "rg" to "ripgrep 搜索",
            "xargs" to "参数传递",
            "tee" to "输出分流",
            "rsync" to "同步",
            "diff" to "比较",
            "tar" to "打包",
            "zip" to "压缩",
            "unzip" to "解压",
            "make" to "Make 构建",
            "cmake" to "CMake 构建",
            "gradle" to "Gradle 构建",
            "mvn" to "Maven 构建",
            "go_build" to "Go 编译",
            "go_test" to "Go 测试",
            "npm_run" to "npm 脚本",
            "npm_test" to "npm 测试",
            "translate" to "翻译",
            "summarize" to "总结",
            "analyze" to "分析",
            "deploy" to "部署",
            "rollback" to "回滚",
            "monitor" to "监控",
            "notify" to "通知",
            "backup" to "备份",
            "restore" to "恢复",
            "schedule" to "定时任务",
            "cron" to "定时任务",
            "scheduler" to "调度器",
            "webhook" to "Webhook",
            "email" to "邮件",
            "smtp" to "SMTP 发送",
            "imap" to "IMAP 收信",
            "telegram" to "Telegram",
            "wechat" to "微信",
            "dingtalk" to "钉钉",
            "feishu" to "飞书",
            "webdav" to "WebDAV",
            "s3" to "S3 存储",
            "oss" to "OSS 存储",
            "ftp" to "FTP",
            "sftp" to "SFTP",
            "ntp" to "时间同步",
            "dns" to "DNS 查询",
            "curl_get" to "GET 请求",
            "curl_post" to "POST 请求",
            "http" to "HTTP 请求",
            "rest" to "REST API",
            "api" to "API 调用",
            "env" to "环境变量",
            "export" to "导出变量",
            "echo" to "输出",
            "printf" to "格式化输出",
            "sleep" to "等待",
            "timeout" to "超时控制",
            "watch" to "监视",
            "service" to "服务管理",
            "uname" to "系统信息",
            "whoami" to "当前用户",
            "hostname" to "主机名",
            "openssl" to "加密工具",
            "base64" to "Base64 编码",
            "md5" to "MD5 校验",
            "sha256" to "SHA256 校验",
            "yq" to "YAML 处理",
            "grep" to "搜索文本",
            "ag" to "代码搜索",
            "date" to "日期时间",
            "history" to "历史",
            "help" to "帮助",
            "man" to "手册",
            "which" to "查找命令",
            "file" to "文件类型",
            "stat" to "文件状态",
            "chmod" to "权限修改",
            "chown" to "所有者修改",
            "ln" to "链接",
            "mount" to "挂载",
            "apt" to "软件包管理",
            "apt-get" to "软件包管理",
            "yum" to "软件包管理",
            "pip" to "Python 包",
            "pip3" to "Python 包",
            "cargo" to "Rust 包",
            "go" to "Go 工具",
            "yarn" to "Yarn 包",
            "pnpm" to "pnpm 包",
            "bun" to "Bun 包",
            "test" to "测试",
            "debug" to "调试",
            "lint" to "代码检查",
            "validate" to "验证",
            "convert" to "转换",
            "format" to "格式化",
            "download" to "下载",
            "upload" to "上传",
            "sync" to "同步",
            "import" to "导入",
            "export_data" to "导出",
            "query" to "查询",
            "insert" to "插入",
            "update_data" to "更新",
            "delete_data" to "删除",
            "commit" to "提交事务",
            "transaction" to "事务",
            "cache" to "缓存",
            "clear_cache" to "清缓存",
            "restart" to "重启",
            "stop" to "停止",
            "start_service" to "启动服务",
            "pause" to "暂停",
            "resume" to "恢复",
            "cancel" to "取消",
            "retry" to "重试",
            "undo" to "撤销",
            "redo" to "重做",
            "log" to "日志",
            "metrics" to "指标",
            "stats" to "统计",
            "job" to "任务",
            "workflow" to "工作流",
            "pipeline" to "管道",
            "event" to "事件",
            "trigger" to "触发",
            "subscribe" to "订阅",
            "unsubscribe" to "取消订阅",
            "publish" to "发布",
            "broadcast" to "广播",
            "rpc" to "远程调用",
            "grpc" to "gRPC 调用",
            "graphql" to "GraphQL",
            "websocket" to "WebSocket",
            "sse" to "SSE 流",
            "mqtt" to "MQTT",
            "kafka" to "Kafka",
            "redis_pubsub" to "Redis 发布订阅",
            "minio" to "MinIO",
            "google_drive" to "Google Drive",
            "onedrive" to "OneDrive",
            "dropbox" to "Dropbox",
        )

    /** 展示名最大长度（未收录超长名截断，防折叠条溢出） */
    private const val MAX_NAME_LEN = 40

    /** 展示名：英文「中文」；未收录 → 原样返回（超长截断 + 省略号） */
    fun display(name: String): String {
        val zh = MAP[name] ?: return truncate(name)
        return "${truncate(name)}「$zh」"
    }

    private fun truncate(name: String): String =
        if (name.length > MAX_NAME_LEN) name.take(MAX_NAME_LEN - 1) + "…" else name
}
